=== DanielHalachev/Bachelor-Code-Materials/Semester 5/XML/2/5.dtd
<!ELEMENT channel (item+,title,link,image*,language?,description)>
<!ATTLIST channel version CDATA #REQUIRED>
<!ELEMENT item (
    (title,link,description?)|
    (title,desciption?,link)|
    (link, title, description?)|
    (link, decription?, title)|
    (description?, title, link)|
    (description?, link, title))>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image (title*|link*|url*)>
<!ELEMENT language EMPTY>

=== DanielHalachev/Bachelor-Code-Materials/Semester 5/XML/2/5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE channel SYSTEM "5.dtd">
<channel version="">
    <item>
        <title></title>
        <link></link>
        <description></description>
    </item>
    <title></title>
    <link></link>
    <image>
        <title></title>
    </image>
    <language></language>
    <description></description>
</channel>
