=== DanielHalachev/Bachelor-Code-Materials/Semester 5/XML/2/6.dtd
<!ELEMENT games (game)*>
<!ELEMENT game (teams, goals, suspensions)>
<!ATTLIST game score NMTOKEN #REQUIRED>
<!ELEMENT teams (home, guest)>
<!ELEMENT home (#PCDATA)>
<!ELEMENT guest (#PCDATA)>
<!ELEMENT goals (goal)*>
<!ELEMENT goal (player, time)>
<!ELEMENT player (#PCDATA)>
<!ELEMENT time (#PCDATA)>
<!ELEMENT suspensions (reds, yellows)>
<!ELEMENT reds (player, player)>
<!ELEMENT yellows (player, player)>

=== DanielHalachev/Bachelor-Code-Materials/Semester 5/XML/2/6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE games SYSTEM "6.dtd">
<games>
    <game score="1-1">
        <teams>
            <home></home>
            <guest></guest>
        </teams>
        <goals>
            <goal>
                <player></player>
                <time></time>
            </goal>
        </goals>
        <suspensions>
            <reds>
                <player></player>
                <player></player>
            </reds>
            <yellows>
                <player></player>
                <player></player>
            </yellows>
        </suspensions>
    </game>
</games>
