=== DanielHalachev/Bachelor-Code-Materials/Semester 5/XML/3/1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="collection">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="xs:anySimpleType"></xs:element>
                <xs:sequence>
                    <xs:element name="recipe" minOccurs="0" maxOccurs="unbounded">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="title" type="xs:string"></xs:element>
                                <xs:sequence>
                                    <xs:element name="ingredient" minOccurs="0" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:complexContent>
                                                <xs:extension base="prep">
                                                    <xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
                                                    <xs:attribute name="anySimpleType" type="xs:string" use="optional"></xs:attribute>
                                                    <xs:attribute name="unit" type="xs:string" use="optional"></xs:attribute>
                                                </xs:extension>
                                            </xs:complexContent>
                                        </xs:complexType>
                                    </xs:element>
                                    <xs:element name="preparation"></xs:element>
                                    <xs:element name="comment" minOccurs="0" maxOccurs="1"></xs:element>
                                    <xs:element name="nutrition">
                                        <xs:complexType>
                                            <xs:attribute name="protein" type="xs:string" use="required"></xs:attribute>
                                            <xs:attribute name="carbohydrates" type="xs:string" use="required"></xs:attribute>
                                            <xs:attribute name="fat" type="xs:string" use="required"></xs:attribute>
                                            <xs:attribute name="calories" type="xs:string" use="required"></xs:attribute>
                                            <xs:attribute name="alcohol" type="xs:string" use="optional"></xs:attribute>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="prep">
        <xs:sequence>
            <xs:element name="step" minOccurs="0" maxOccurs="unbounded"></xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== DanielHalachev/Bachelor-Code-Materials/Semester 5/XML/3/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<collection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="1.xsd">
    <description> Hello </description>
    <recipe>
        <title>MyRecipe</title>
        <ingredient name="butter"></ingredient>
        <ingredient name="milk"></ingredient>
        <ingredient name="cookie">
            <step>Buy cookies from store</step>
        </ingredient>
        <preparation>
            <step>Heat the butter</step>
            <step>Heat the milk</step>
            <step>Mix Together</step>
        </preparation>
        <comment>This recipe is fake</comment>
        <nutrition protein="1" carbohydrates="2" fat="3" calories="4" />
    </recipe>
</collection>
