=== DanielHalachev/Bachelor-Code-Materials/Semester 5/XML/University Catalog/catalog.dtd
<!ELEMENT catalog (universities,regions)>
<!ATTLIST catalog
    xmlns:xsi CDATA #IMPLIED
    xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT universities (university+)>
<!ELEMENT university (name,description,chancellor,location,contacts,website,statistics,faculties,image)>
<!ATTLIST university id ID #REQUIRED>
<!ATTLIST university regionID NMTOKEN #REQUIRED>
<!ATTLIST university branchOf NMTOKEN #IMPLIED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT chancellor (#PCDATA)>
<!ATTLIST chancellor degree CDATA #REQUIRED>
<!ELEMENT location (city,address,postcode)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT contacts (phone,email,fax?)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ELEMENT website EMPTY>
<!ATTLIST website href CDATA #REQUIRED>
<!ELEMENT statistics (students,lecturers,since)>
<!ELEMENT students (#PCDATA)>
<!ELEMENT lecturers (#PCDATA)>
<!ELEMENT since (#PCDATA)>
<!ELEMENT faculties (faculty+)>
<!ELEMENT faculty (#PCDATA)>
<!ATTLIST faculty acronym CDATA #IMPLIED>
<!ELEMENT image EMPTY>
<!ATTLIST image src ENTITY #REQUIRED>
<!ELEMENT regions (region+)>
<!ELEMENT region (#PCDATA)>
<!ATTLIST region id NMTOKEN #REQUIRED>

=== DanielHalachev/Bachelor-Code-Materials/Semester 5/XML/University Catalog/catalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="catalog.xsl" type="text/xsl"?>
<!DOCTYPE catalog SYSTEM "catalog.dtd" [
    <!NOTATION jpg SYSTEM "image/jpg">
    <!ENTITY su SYSTEM "images/su.jpg" NDATA jpg>
    <!ENTITY tu SYSTEM "images/tu.jpg" NDATA jpg>
    <!ENTITY nbu SYSTEM "images/nbu.jpg" NDATA jpg>
    <!ENTITY pu SYSTEM "images/pu.jpg" NDATA jpg>
    <!ENTITY tu-plovdiv SYSTEM "images/tu-plovdiv.jpg" NDATA jpg>
    <!ENTITY pu-smolian SYSTEM "images/pu-smolian.jpg" NDATA jpg>
    <!ENTITY tru SYSTEM "images/tru.jpg" NDATA jpg>
    <!ENTITY btu SYSTEM "images/btu.jpg" NDATA jpg>
    <!ENTITY bfu SYSTEM "images/bfu.jpg" NDATA jpg>
    <!ENTITY tu-sliven SYSTEM "images/tu-sliven.jpg" NDATA jpg>
    <!ENTITY mu SYSTEM "images/mu.jpg" NDATA jpg>
    <!ENTITY vtu SYSTEM "images/vtu.jpg" NDATA jpg>
    <!ENTITY vfu SYSTEM "images/vfu.jpg" NDATA jpg>
]>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="catalog.xsd">
    <universities>
        <university id="u1" regionID="sw">
            <name>Софийски университет "Св. Климент Охридски"</name>
            <description>Софийският университет „Св. Климент Охридски“ или съкратено СУ „Св. Климент
                Охридски“ е най-старото и най-голямо висше училище в България. Неговата история е
                въплъщение и продължение на многовековната културна и просветна традиция на
                българския народ. Научноизследователската дейност на преподавателите от Софийския
                университет „Св. Климент Охридски“ е съставна част от учебния процес със студентите.</description>
            <chancellor degree="Проф. дфн.">Анастас Герджиков</chancellor>
            <location>
                <city>София</city>
                <address>бул. "Цар Освободител" 15</address>
                <postcode>1504</postcode>
            </location>
            <contacts>
                <phone>02/ 93 08 200</phone>
                <email>info@uni-sofia.bg</email>
                <fax>02/ 94 60 255</fax>
            </contacts>
            <website href="www.uni-sofia.bg" />
            <statistics>
                <students>20516</students>
                <lecturers>1711</lecturers>
                <since>1888</since>
            </statistics>
            <faculties>
                <faculty acronym="ИФ">Исторически факултет</faculty>
                <faculty acronym="ФФ">Философски факултет</faculty>
                <faculty acronym="ФКНФ">Факултет по класически и нови филологии</faculty>
                <faculty acronym="ФСФ">Факултет по славянски филологии</faculty>
                <faculty acronym="ЮФ">Юридически факултет</faculty>
                <faculty acronym="ФП">Факултет по педагогика</faculty>
                <faculty acronym="ФНОИ">Факултет по науки за образованието и изкуствата</faculty>
                <faculty acronym="ФЖМК">Факултет по журналистика и масова комуникация</faculty>
                <faculty acronym="БгФ">Богословски факултет</faculty>
                <faculty acronym="СФ">Стопански факултет</faculty>
                <faculty acronym="ФМИ">Факултет по математика и информатика</faculty>
                <faculty acronym="ФзФ">Физически факултет</faculty>
                <faculty acronym="ФХФ">Факултет по химия и фармация</faculty>
                <faculty acronym="БФ">Биологически факултет</faculty>
                <faculty acronym="ГгФ">Геолого-географски факултет</faculty>
                <faculty acronym="МФ">Медицински факултет</faculty>
            </faculties>
            <image src="su" />
        </university>
        <university id="u2" regionID="sw">
            <name>Технически университет - София</name>
            <description>Техническият университет в гр. София е държавно техническо висше училище,
                най-голямото в България. В учебната си структура ТУС включва общо 17 факултета и 3
                департамента, 3 висши колежа и 2 средни училища в няколко града. Техническият
                университет осъществява методично и учебно ръководство на 2 средни технически
                училища – в София и Правец.</description>
            <chancellor degree="Проф. дн. инж.">Иван Кралов</chancellor>
            <location>
                <city>София</city>
                <address>бул. "Св. Климент Охридски" 8</address>
                <postcode>1000</postcode>
            </location>
            <contacts>
                <phone>02/ 862 3073</phone>
                <email>ucheben@tu-sofia.bg</email>
                <fax>02/ 868 3215</fax>
            </contacts>
            <website href="www.tu-sofia.bg" />
            <statistics>
                <students>11005</students>
                <lecturers>704</lecturers>
                <since>1945</since>
            </statistics>
            <faculties>
                <faculty acronym="ФА">Факултет по автоматика</faculty>
                <faculty acronym="ЕлФ">Електротехнически факултет</faculty>
                <faculty acronym="ЕнФ">Енергомашиностроителен факултет</faculty>
                <faculty acronym="МФ">Машиностроителен факултет</faculty>
                <faculty acronym="ФЕТТ">Факултет по електронна техника и технологии</faculty>
                <faculty acronym="ФТ">Факултет по телекомуникации</faculty>
                <faculty acronym="ФКСТ">Факултет по компютърни системи и технологии</faculty>
                <faculty acronym="ФТ">Факултет по транспорта</faculty>
                <faculty acronym="СФ">Стопански факултет</faculty>
                <faculty acronym="ФПМИ">Факултет по приложна математика и информатика</faculty>
                <faculty acronym="ФГИОП">Факултет за германско инженерно обучение и промишленост</faculty>
                <faculty acronym="ФФОЕ">Факултет за френско обучение по електроинженерство</faculty>
                <faculty acronym="ФАИО">Факултет за английско инженерно обучение</faculty>
                <faculty acronym="ФИТ">Факултет по индустриални технологии</faculty>
            </faculties>
            <image src="tu" />
        </university>
        <university id="u3" regionID="sw">
            <name>Нов български университет - София</name>
            <description>Нов български университет (съкратено НБУ) е български частен университет.
                Основната му база е разположена в София, в няколко корпуса, като притежава и други
                академични бази из страната, а също и собствена университетска библиотека в София –
                Библиотека на НБУ. Университетът разполага със собствено издателство. </description>
            <chancellor degree="Проф. дн.">Пламен Дойнов</chancellor>
            <location>
                <city>София</city>
                <address>ул. "Монтевидео" 21</address>
                <postcode>1618</postcode>
            </location>
            <contacts>
                <phone>02/ 81 10 571</phone>
                <email>ealexandrova@nbu.bg</email>
            </contacts>
            <website href="nbu.bg" />
            <statistics>
                <students>9620</students>
                <lecturers>361</lecturers>
                <since>1991</since>
            </statistics>
            <faculties>
                <faculty acronym="ФБО">Факултет за базово образование</faculty>
                <faculty acronym="БФ">Бакалавърски факултет</faculty>
                <faculty acronym="МФ">Магистърски факултет</faculty>
                <faculty acronym="МДЕНО">Факултет за дистанционно, електронно и надграждащо
обучение</faculty>
            </faculties>
            <image src="nbu" />
        </university>
        <university id="u4" regionID="sc">
            <name>Пловдивски университет "Паисий Хилендарски"</name>
            <description>Пловдивският университет „Паисий Хилендарски“ (или ПУ) е висше училище в
                Пловдив, Смолян и Кърджали, България. Той е водеща културна, образователна и научна
                институция. Днес Пловдивският университет „Паисий Хилендарски“ има 9 факултета, в
                които се обучават над 8000 редовни и около 5000 задочни студенти в повече от 40
                специалности по природни, хуманитарни, обществени и икономически науки.</description>
            <chancellor degree="Проф. др.">Румен Младенов</chancellor>
            <location>
                <city>Пловдив</city>
                <address>ул. "Цар Асен" 24</address>
                <postcode>4000</postcode>
            </location>
            <contacts>
                <phone>032/ 261 261</phone>
                <email>diana_ilieva@uni-plovdiv.bg</email>
                <fax>032/ 628 390</fax>
            </contacts>
            <website href="www.uni-plovdiv.bg" />
            <statistics>
                <students>16960</students>
                <lecturers>628</lecturers>
                <since>1961</since>
            </statistics>
            <faculties>
                <faculty>Биологически факултет</faculty>
                <faculty>Факултет по икономически и социални науки</faculty>
                <faculty>Факултет по математика и информатика</faculty>
                <faculty>Философско-исторически факултет</faculty>
                <faculty>Педагогически факултет</faculty>
                <faculty>Физико-технологичен факултет</faculty>
                <faculty>Филологически факултет</faculty>
                <faculty>Философско-исторически факултет</faculty>
                <faculty>Химически факултет</faculty>
                <faculty>Юридически факултет</faculty>
            </faculties>
            <image src="pu" />
        </university>
        <university id="u5" regionID="sc" branchOf="u2">
            <name>Технически университет - София, филиал Пловдив</name>
            <description>Филиалът е създаден през 1986 г. като изнесено звено на Технически
                Университет (ТУ) - София на територията на гр. Пловдив. Филиалът има богата
